#nullable enable

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Kassyi.Generators.DependencyProperty.Generators;
using Kassyi.Generators.Extensions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Kassyi.Generators.DependencyProperty.SnapshotTests;

/// <summary>Validates all valid permutations of dependency property generation across target UI frameworks.</summary>
[TestClass]
[TestCategory(TestCategoryNames.Matrix)]
public class CombinatorialMatrixTests : SnapshotTestBase
{
    public enum AttrType { Normal, Attached }
    public enum ClassMode { PublicClass, InternalGenericClass, PublicRecord, StaticClass }
    public enum PropType { Int, NullableInt, String, GenericList }
    public enum ReadOnlyMode { False, True }
    public enum DefaultMode { None, Literal, Expression }
    public enum DirectMode { False, True }

    private static readonly Framework[] SupportedFrameworks = { Framework.Wpf, Framework.Uno, Framework.UnoWinUi, Framework.Maui, Framework.Avalonia };

    [DataTestMethod]
    [TestCategory(TestCategoryNames.Matrix)]
    [DataRow(Framework.Wpf)]
    [DataRow(Framework.Uno)]
    [DataRow(Framework.UnoWinUi)]
    [DataRow(Framework.Maui)]
    [DataRow(Framework.Avalonia)]
    public async Task RunCombinatorialMatrix(Framework framework)
    {
        var source = BuildUnifiedMatrixSource(framework);

        var (compilation, driver) = await CreateCompilationAndDriverAsync<DependencyPropertyGenerator>(
            source,
            framework,
            cancellationToken: default,
            new AttachedDependencyPropertyGenerator()
        );

        driver = driver.RunGeneratorsAndUpdateCompilation(compilation, out compilation, out var generatorDiagnostics, default);
        
        var diagnostics = compilation.GetDiagnostics(default).Concat(generatorDiagnostics);

        // [WHY] Fail immediately if there are Roslyn compilation errors (CSxxxx). Warnings like CS8600/CS8019 are non-blocking.
        var errors = diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error).ToArray();
        if (errors.Length > 0)
        {
            DemultiplexAndFail(errors, compilation.SyntaxTrees.First().GetRoot());
        }

        var generatedSources = driver.GetRunResult().Results.SelectMany(r => r.GeneratedSources).ToArray();
        Assert.IsTrue(generatedSources.Length > 0, "No source files were generated by DPG.");

        // [WHY] Ensures generator did not silently drop/skip any valid properties by validating input attribute count vs output property field count.
        var inputRoot = compilation.SyntaxTrees.First().GetRoot();
        var outputRoots = generatedSources.Select(g => g.SyntaxTree.GetRoot()).ToArray();

        try
        {
            E2EAssertionPipeline.VerifyCountMatching(inputRoot, outputRoots, framework);
        }
        catch (Exception)
        {
            DemultiplexAssertionFailure(inputRoot, outputRoots);
            throw; // Fallback if DemultiplexAssertionFailure didn't throw
        }
    }

    private static void DemultiplexAssertionFailure(SyntaxNode inputRoot, SyntaxNode[] outputRoots)
    {
        var inputClasses = inputRoot.DescendantNodes().OfType<Microsoft.CodeAnalysis.CSharp.Syntax.TypeDeclarationSyntax>().ToList();
        var outputClasses = outputRoots.SelectMany(r => r.DescendantNodes().OfType<Microsoft.CodeAnalysis.CSharp.Syntax.TypeDeclarationSyntax>()).ToList();

        foreach (var inputClass in inputClasses)
        {
            var className = inputClass.Identifier.ValueText;
            if (!className.StartsWith("TestClass_")) continue;

            var targetAttributes = inputClass.AttributeLists.SelectMany(al => al.Attributes).ToList();
            int expectedCount = targetAttributes.Count;
            if (expectedCount == 0) continue;

            var targetOutputClasses = outputClasses.Where(c => c.Identifier.ValueText == className).ToList();
            int generatedCount = 0;
            if (targetOutputClasses.Count > 0)
            {
                generatedCount = targetOutputClasses.SelectMany(c => c.Members.OfType<Microsoft.CodeAnalysis.CSharp.Syntax.FieldDeclarationSyntax>()).Count(f => {
                    var typeName = f.Declaration.Type.ToString();
                    return typeName.Contains("Property") && !typeName.Contains("PropertyKey");
                });
            }

            if (generatedCount != expectedCount)
            {
                Assert.Fail($"Assertion failed. Expected {expectedCount} generated property fields, but found {generatedCount}.\nIn combination: {ParseCombinationFromClassName(className)}");
            }
        }
    }

    private static void DemultiplexAndFail(Diagnostic[] errors, SyntaxNode root)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"Found {errors.Length} compilation errors:");
        foreach (var error in errors)
        {
            var span = error.Location.SourceSpan;
            var node = root.FindNode(span);
            var classDecl = node.AncestorsAndSelf().OfType<Microsoft.CodeAnalysis.CSharp.Syntax.TypeDeclarationSyntax>().FirstOrDefault();
            var className = classDecl?.Identifier.ValueText ?? "UnknownClass";
            sb.AppendLine($"- Error: {error.Id} {error.GetMessage()}");
            sb.AppendLine($"  In combination: {ParseCombinationFromClassName(className)}");
        }
        Assert.Fail(sb.ToString());
    }

    private static string ParseCombinationFromClassName(string className)
    {
        if (className.StartsWith("TestClass_"))
        {
            var parts = className.Substring("TestClass_".Length).Split('_');
            if (parts.Length == 6)
            {
                return $"Attr={parts[0]}, Class={parts[1]}, Prop={parts[2]}, ReadOnly={parts[3]}, Default={parts[4]}, Direct={parts[5]}";
            }
        }
        return className;
    }

    private static string BuildUnifiedMatrixSource(Framework framework)
    {
        using var writer = new SourceWriter();
        writer.AppendLine("#nullable enable");
        writer.AppendLine("using System.Collections.Generic;");
        writer.AppendLine(GetHeader(framework, nullable: true, @namespace: false, "Controls", "System"));

        using (writer.Scope("namespace MyControls"))
        {
            foreach (AttrType attr in Enum.GetValues<AttrType>())
            foreach (ClassMode cls in Enum.GetValues<ClassMode>())
            foreach (PropType prop in Enum.GetValues<PropType>())
            foreach (ReadOnlyMode ro in Enum.GetValues<ReadOnlyMode>())
            foreach (DefaultMode def in Enum.GetValues<DefaultMode>())
            foreach (DirectMode dir in Enum.GetValues<DirectMode>())
            {
                if (IsValidCombination(framework, attr, cls, prop, ro, def, dir))
                {
                    GenerateClass(framework, writer, attr, cls, prop, ro, def, dir);
                }
            }
        }

        return writer.ToString();
    }

    private static bool IsValidCombination(
        Framework framework,
        AttrType attr,
        ClassMode cls,
        PropType prop,
        ReadOnlyMode ro,
        DefaultMode def,
        DirectMode dir)
    {
        // [WHY] DirectProperty is only valid for normal properties on Avalonia.
        if (dir == DirectMode.True && !(framework == Framework.Avalonia && attr == AttrType.Normal))
            return false;

        // [WHY] Records cannot inherit from UserControl, so normal DPs are not supported.
        if (cls == ClassMode.PublicRecord && attr == AttrType.Normal)
            return false;

        // [WHY] Static class can only be used with Attached properties.
        if (cls == ClassMode.StaticClass && attr != AttrType.Attached)
            return false;

        // [WHY] GenericList cannot have Literal or Expression default values (they are reference types and trigger DPG0004). Only None is valid.
        if (prop == PropType.GenericList && def != DefaultMode.None)
            return false;

        // [WHY] Value types like int use constant literals, not expressions.
        if (prop == PropType.Int && def == DefaultMode.Expression)
            return false;

        return true;
    }

    private static void GenerateClass(
        Framework framework,
        SourceWriter writer,
        AttrType attr,
        ClassMode cls,
        PropType prop,
        ReadOnlyMode ro,
        DefaultMode def,
        DirectMode dir)
    {
        var attrName = attr == AttrType.Normal ? "DependencyProperty" : "AttachedDependencyProperty";
        var typeName = GetTypeName(prop);
        var attributeArgs = BuildAttributeArguments(ro, def, dir, prop);
        var className = $"TestClass_{attr}_{cls}_{prop}_{ro}_{def}_{dir}";
        var classDeclaration = GetClassDeclaration(mode: cls, framework: framework, className: className);

        var attributeDeclaration = $"[{attrName}(\"MyProperty\", typeof({typeName}){attributeArgs})]";

        writer.AppendLine($"    {attributeDeclaration}");
        using (writer.Scope($"    {classDeclaration}"))
        {
        }
    }

    private static string GetTypeName(PropType type) => type switch
    {
        PropType.Int => "int",
        PropType.NullableInt => "int?",
        PropType.String => "string",
        PropType.GenericList => "List<int>",
        _ => "object"
    };

    private static string BuildAttributeArguments(ReadOnlyMode ro, DefaultMode def, DirectMode dir, PropType prop)
    {
        var args = new List<string>();
        if (ro == ReadOnlyMode.True) args.Add("IsReadOnly = true");
        if (dir == DirectMode.True) args.Add("IsDirect = true");

        var defaultValueArg = GetDefaultValueArgument(def, prop);
        if (defaultValueArg is not null)
        {
            args.Add(defaultValueArg);
        }

        return args.Count > 0 ? ", " + string.Join(", ", args) : string.Empty;
    }

    private static string? GetDefaultValueArgument(DefaultMode mode, PropType type) => (mode, type) switch
    {
        (DefaultMode.Literal, PropType.Int or PropType.NullableInt) => "DefaultValue = 123",
        (DefaultMode.Literal, PropType.String)                     => "DefaultValue = \"abc\"",
        (DefaultMode.Expression, PropType.String)                  => "DefaultValueExpression = \"\\\"def\\\"\"", // Generates: DefaultValueExpression = "\"def\""
        (DefaultMode.Expression, PropType.GenericList)             => "DefaultValueExpression = \"[]\"",
        _ => null
    };

    private static string GetClassDeclaration(ClassMode mode, Framework framework, string className) => mode switch
    {
        ClassMode.PublicClass          => $"public partial class {className} : {FrameworkTestData.GetUserControl(framework)}",
        ClassMode.InternalGenericClass => $"internal partial class {className}<T> : {FrameworkTestData.GetUserControl(framework)}",
        ClassMode.PublicRecord         => $"public partial record {className}",
        ClassMode.StaticClass          => $"public static partial class {className}",
        _                              => string.Empty
    };
}
