#nullable enable

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Kassyi.Generators.DependencyProperty.Generators;
using Kassyi.Generators.Extensions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Kassyi.Generators.DependencyProperty.SnapshotTests;

/// <summary>Validates all valid permutations of dependency property generation across target UI frameworks.</summary>
[TestClass]
[TestCategory(TestCategoryNames.Matrix)]
public class CombinatorialMatrixTests : SnapshotTestBase
{
    public enum AttrType { Normal, Attached }
    public enum ClassMode { PublicClass, InternalGenericClass, PublicRecord, StaticClass }
    public enum PropType { Int, NullableInt, String, GenericList }
    public enum ReadOnlyMode { False, True }
    public enum DefaultMode { None, Literal, Expression }
    public enum DirectMode { False, True }

    public static IEnumerable<object[]> GetMatrixData()
    {
        var supportedFrameworks = new[] { Framework.Wpf, Framework.Uno, Framework.UnoWinUi, Framework.Maui, Framework.Avalonia };
        foreach (var framework in supportedFrameworks)
        {

            foreach (AttrType attr in Enum.GetValues<AttrType>())
            foreach (ClassMode cls in Enum.GetValues<ClassMode>())
            foreach (PropType prop in Enum.GetValues<PropType>())
            foreach (ReadOnlyMode ro in Enum.GetValues<ReadOnlyMode>())
            foreach (DefaultMode def in Enum.GetValues<DefaultMode>())
            foreach (DirectMode dir in Enum.GetValues<DirectMode>())
            {
                if (IsValidCombination(framework, attr, cls, prop, ro, def, dir))
                {
                    yield return new object[] { framework, attr, cls, prop, ro, def, dir };
                }
            }
        }
    }

    [DataTestMethod]
    [TestCategory($"{TestCategoryNames.Matrix}-001")]
    [DynamicData(nameof(GetMatrixData), DynamicDataSourceType.Method)]
    public async Task RunCombinatorialMatrix(
        Framework framework,
        AttrType attr,
        ClassMode cls,
        PropType prop,
        ReadOnlyMode ro,
        DefaultMode def,
        DirectMode dir)
    {
        var source = BuildSingleMatrixSource(framework, attr, cls, prop, ro, def, dir);

        var (compilation, driver) = await CreateCompilationAndDriverAsync<DependencyPropertyGenerator>(
            source,
            framework,
            cancellationToken: default,
            new AttachedDependencyPropertyGenerator()
        );

        driver = driver.RunGeneratorsAndUpdateCompilation(compilation, out compilation, out var generatorDiagnostics, default);
        var diagnostics = compilation.GetDiagnostics(default).Concat(generatorDiagnostics);

        // [WHY] Fail immediately if there are Roslyn compilation errors (CSxxxx). Warnings like CS8600/CS8019 are non-blocking.
        var errors = diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error).ToArray();
        if (errors.Length > 0)
        {
            Assert.Fail($"Found {errors.Length} compilation errors.\nFirst error: {errors[0].GetMessage()}\n\nSource snippet:\n{source}");
        }

        var generatedSources = driver.GetRunResult().Results.SelectMany(r => r.GeneratedSources).ToArray();
        Assert.IsTrue(generatedSources.Length > 0, "No source files were generated by DPG.");

        // [WHY] Ensures generator did not silently drop/skip any valid properties by validating input attribute count vs output property field count.
        var inputRoot = CSharpSyntaxTree.ParseText(source).GetRoot();
        var outputRoots = generatedSources.Select(g => g.SyntaxTree.GetRoot()).ToArray();
        E2EAssertionPipeline.VerifyCountMatching(inputRoot, outputRoots, framework);
    }

    private static string BuildSingleMatrixSource(
        Framework framework,
        AttrType attr,
        ClassMode cls,
        PropType prop,
        ReadOnlyMode ro,
        DefaultMode def,
        DirectMode dir)
    {
        // [WHY] Uses SourceWriter and Scope() to eliminate heap allocations and prevent structural brace-mismatch errors.
        using var writer = new SourceWriter();
        writer.AppendLine("#nullable enable");
        writer.AppendLine("using System.Collections.Generic;");
        writer.AppendLine(GetHeader(framework, nullable: true, @namespace: false, "Controls", "System"));

        using (writer.Scope("namespace MyControls"))
        {
            GenerateClass(writer, attr, cls, prop, ro, def, dir);
        }

        return writer.ToString();
    }

    private static bool IsValidCombination(
        Framework framework,
        AttrType attr,
        ClassMode cls,
        PropType prop,
        ReadOnlyMode ro,
        DefaultMode def,
        DirectMode dir) =>
        // [WHY] DirectProperty is only valid for normal properties on Avalonia.
        (dir, framework) is not (DirectMode.True, not Framework.Avalonia)
        && (dir, attr) is not (DirectMode.True, not AttrType.Normal)

        // [WHY] Records cannot inherit from UserControl, so normal DPs are not supported.
        && (cls, attr) is not (ClassMode.PublicRecord, AttrType.Normal)

        // [WHY] Static class can only be used with Attached properties.
        && (cls, attr) is not (ClassMode.StaticClass, not AttrType.Attached)

        // [WHY] GenericList cannot have Literal or Expression default values (they are reference types and trigger DPG0004). Only None is valid.
        && (prop, def) is not (PropType.GenericList, not DefaultMode.None)

        // [WHY] Value types like int use constant literals, not expressions.
        && (prop, def) is not (PropType.Int, DefaultMode.Expression);

    private static void GenerateClass(
        SourceWriter writer,
        AttrType attr,
        ClassMode cls,
        PropType prop,
        ReadOnlyMode ro,
        DefaultMode def,
        DirectMode dir)
    {
        var attrName = attr == AttrType.Normal ? "DependencyProperty" : "AttachedDependencyProperty";
        var typeName = GetTypeName(prop);
        var attributeArgs = BuildAttributeArguments(ro, def, dir, prop);
        var classDeclaration = GetClassDeclaration(cls);

        var attributeDeclaration = $"[{attrName}(\"MyProperty\", typeof({typeName}){attributeArgs})]";

        writer.AppendLine($"    {attributeDeclaration}");
        using (writer.Scope($"    {classDeclaration}"))
        {
        }
    }

    private static string GetTypeName(PropType type) => type switch
    {
        PropType.Int => "int",
        PropType.NullableInt => "int?",
        PropType.String => "string",
        PropType.GenericList => "List<int>",
        _ => "object"
    };

    private static string BuildAttributeArguments(ReadOnlyMode ro, DefaultMode def, DirectMode dir, PropType prop)
    {
        var args = new List<string>();
        if (ro == ReadOnlyMode.True) args.Add("IsReadOnly = true");
        if (dir == DirectMode.True) args.Add("IsDirect = true");

        var defaultValueArg = GetDefaultValueArgument(def, prop);
        if (defaultValueArg is not null)
        {
            args.Add(defaultValueArg);
        }

        return args.Count > 0 ? ", " + string.Join(", ", args) : string.Empty;
    }

    private static string? GetDefaultValueArgument(DefaultMode mode, PropType type) => (mode, type) switch
    {
        (DefaultMode.Literal, PropType.Int or PropType.NullableInt) => "DefaultValue = 123",
        (DefaultMode.Literal, PropType.String)                     => "DefaultValue = \"abc\"",
        (DefaultMode.Expression, PropType.String)                  => "DefaultValueExpression = \"\\\"def\\\"\"", // Generates: DefaultValueExpression = "\"def\""
        (DefaultMode.Expression, PropType.GenericList)             => "DefaultValueExpression = \"[]\"",
        _ => null
    };

    private static string GetClassDeclaration(ClassMode mode) => mode switch
    {
        ClassMode.PublicClass          => $"public partial class TestClass : UserControl",
        ClassMode.InternalGenericClass => $"internal partial class TestClass<T> : UserControl",
        ClassMode.PublicRecord         => $"public partial record TestClass",
        ClassMode.StaticClass          => $"public static partial class TestClass",
        _                              => string.Empty
    };
}
