#nullable enable

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Kassyi.Generators.DependencyProperty.Generators;
using Kassyi.Generators.Extensions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Kassyi.Generators.DependencyProperty.SnapshotTests;

/// <summary>Validates all valid permutations of dependency property generation across target UI frameworks.</summary>
[TestClass]
public class CombinatorialMatrixTests : SnapshotTestBase
{
    private enum AttrType { Normal, Attached }
    private enum ClassMode { PublicClass, InternalGenericClass, PublicRecord }
    private enum PropType { Int, NullableInt, String, GenericList }
    private enum ReadOnlyMode { False, True }
    private enum DefaultMode { None, Literal, Expression }
    private enum DirectMode { False, True }

    private readonly record struct TestCase(
        int Id,
        AttrType Attr,
        ClassMode ClassMode,
        PropType PropType,
        ReadOnlyMode ReadOnly,
        DefaultMode DefaultValue,
        DirectMode Direct);

    [TestMethod]
    [DataRow(Framework.Wpf)]
    [DataRow(Framework.Uno)]
    [DataRow(Framework.UnoWinUi)]
    [DataRow(Framework.Maui)]
    [DataRow(Framework.Avalonia)]
    public async Task RunCombinatorialMatrix(Framework framework)
    {
        var source = BuildMatrixSource(framework);

        var (compilation, driver) = await CreateCompilationAndDriverAsync<DependencyPropertyGenerator>(
            source,
            framework,
            cancellationToken: default,
            new AttachedDependencyPropertyGenerator()
        );

        driver = driver.RunGeneratorsAndUpdateCompilation(compilation, out compilation, out var generatorDiagnostics, default);
        var diagnostics = compilation.GetDiagnostics(default).Concat(generatorDiagnostics);

        // [WHY] Fail immediately if there are Roslyn compilation errors (CSxxxx). Warnings like CS8600/CS8019 are non-blocking.
        var errors = diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error).ToArray();
        if (errors.Length > 0)
        {
            Assert.Fail($"Found {errors.Length} compilation errors.\nFirst error: {errors[0].GetMessage()}\n\nSource snippet:\n{source[..Math.Min(1000, source.Length)]}...");
        }

        var generatedSources = driver.GetRunResult().Results.SelectMany(r => r.GeneratedSources).ToArray();
        Assert.IsTrue(generatedSources.Length > 0, "No source files were generated by DPG.");

        // [WHY] Ensures generator did not silently drop/skip any valid properties by validating input attribute count vs output property field count.
        var inputRoot = CSharpSyntaxTree.ParseText(source).GetRoot();
        var outputRoots = generatedSources.Select(g => g.SyntaxTree.GetRoot()).ToArray();
        E2EAssertionPipeline.VerifyCountMatching(inputRoot, outputRoots, framework);
    }

    private string BuildMatrixSource(Framework framework)
    {
        // [WHY] Uses SourceWriter and Scope() to eliminate heap allocations and prevent structural brace-mismatch errors.
        using var writer = new SourceWriter();
        writer.AppendLine("#nullable enable");
        writer.AppendLine("using System.Collections.Generic;");
        writer.AppendLine(GetHeader(framework, nullable: true, @namespace: false, "Controls", "System"));

        using (writer.Scope("namespace MyControls"))
        {
            foreach (var testCase in EnumerateValidCombinations(framework))
            {
                GenerateClass(writer, testCase);
            }
        }

        return writer.ToString();
    }

    private static IEnumerable<TestCase> EnumerateValidCombinations(Framework framework)
    {
        int id = 0;
        foreach (AttrType attr in Enum.GetValues<AttrType>())
        foreach (ClassMode cls in Enum.GetValues<ClassMode>())
        foreach (PropType prop in Enum.GetValues<PropType>())
        foreach (ReadOnlyMode ro in Enum.GetValues<ReadOnlyMode>())
        foreach (DefaultMode def in Enum.GetValues<DefaultMode>())
        foreach (DirectMode dir in Enum.GetValues<DirectMode>())
        {
            var testCase = new TestCase(id, attr, cls, prop, ro, def, dir);
            if (IsValidCombination(framework, testCase))
            {
                yield return testCase;
                id++;
            }
        }
    }

    private static bool IsValidCombination(Framework framework, TestCase test) =>
        // [WHY] DirectProperty is only valid for normal properties on Avalonia.
        (test.Direct, framework) is not (DirectMode.True, not Framework.Avalonia)
        && (test.Direct, test.Attr) is not (DirectMode.True, not AttrType.Normal)

        // [WHY] Records cannot inherit from UserControl, so normal DPs are not supported.
        && (test.ClassMode, test.Attr) is not (ClassMode.PublicRecord, AttrType.Normal)

        // [WHY] GenericList cannot have default values (DPG0004: shared instance bug).
        && (test.PropType, test.DefaultValue) is not (PropType.GenericList, not DefaultMode.None)

        // [WHY] Value types like int use constant literals, not expressions.
        && (test.PropType, test.DefaultValue) is not (PropType.Int, DefaultMode.Expression);

    private static void GenerateClass(SourceWriter writer, TestCase testCase)
    {
        var (id, attr, cls, prop, ro, def, dir) = testCase;

        var attrName = attr == AttrType.Normal ? "DependencyProperty" : "AttachedDependencyProperty";

        var typeStr = prop switch
        {
            PropType.Int => "int",
            PropType.NullableInt => "int?",
            PropType.String => "string",
            PropType.GenericList => "List<int>",
            _ => "object"
        };

        var props = new List<string>();
        if (ro == ReadOnlyMode.True) props.Add("IsReadOnly = true");
        if (dir == DirectMode.True) props.Add("IsDirect = true");

        if (def == DefaultMode.Literal)
        {
            if (prop is PropType.Int or PropType.NullableInt) props.Add("DefaultValue = 123");
            else if (prop == PropType.String) props.Add("DefaultValue = \"abc\"");
        }
        else if (def == DefaultMode.Expression)
        {
            if (prop == PropType.String) props.Add("DefaultValueExpression = \"\\\"def\\\"\"");
            else if (prop == PropType.GenericList) props.Add("DefaultValueExpression = \"[]\"");
        }

        var propsStr = props.Count > 0 ? ", " + string.Join(", ", props) : string.Empty;

        var classDecl = cls switch
        {
            ClassMode.PublicClass => $"public partial class TestClass{id} : UserControl",
            ClassMode.InternalGenericClass => $"internal partial class TestClass{id}<T> : UserControl",
            ClassMode.PublicRecord => $"public partial record TestClass{id}",
            _ => string.Empty
        };

        var attrDecl = $"[{attrName}(\"MyProperty\", typeof({typeStr}){propsStr})]";

        writer.AppendLine($"    {attrDecl}");
        using (writer.Scope($"    {classDecl}"))
        {
        }
    }
}
