using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using Kassyi.Generators.DependencyProperty;

namespace DpgShowcaseCart.Wpf.Controls;

/// <summary>
/// Demonstrates Attached Properties generated by DPG.
/// Eliminates code-behind input validation by attaching behaviors directly via XAML.
/// </summary>
// 6. Attached Properties: Eliminates code-behind input validation by attaching behaviors directly via XAML.
[AttachedDependencyProperty<bool, TextBox>("IsNumericOnly")]
[AttachedDependencyProperty<bool, TextBox>("IsExpiryFormat")]

// 7. Event Binding: DPG automatically handles event subscription/unsubscription (+= and -=) 
// for standard routed events when using the BindEvent attribute parameter.
[AttachedDependencyProperty<object, TextBox>("SelectAllOnFocus", BindEvent = nameof(TextBox.GotKeyboardFocus))]
public static partial class TextBoxInputFilter
{
    // Showcase: DPG automatically handles event subscription/unsubscription (+= and -=) 
    // for standard routed events when using the BindEvent attribute parameter.
    private static void OnSelectAllOnFocusChanged_GotKeyboardFocus(object? sender, KeyboardFocusChangedEventArgs e)
    {
        if (sender is TextBox textBox)
        {
            textBox.SelectAll();
        }
    }

    // 8. Clean Partial Method Signatures: DPG generates multiple overloads for OnChanged.
    // By omitting 'oldValue' here, we keep the signature perfectly clean without IDE0060 (unused parameter) warnings.
    static partial void OnIsNumericOnlyChanged(TextBox textBox, bool newValue)
    {
        if (newValue)
        {
            textBox.PreviewTextInput += OnNumericTextInput;
            DataObject.AddPastingHandler(textBox, OnNumericPasting);
        }
        else
        {
            textBox.PreviewTextInput -= OnNumericTextInput;
            DataObject.RemovePastingHandler(textBox, OnNumericPasting);
        }
    }

    static partial void OnIsExpiryFormatChanged(TextBox textBox, bool newValue)
    {
        if (newValue)
        {
            textBox.PreviewTextInput += OnExpiryTextInput;
            DataObject.AddPastingHandler(textBox, OnExpiryPasting);
        }
        else
        {
            textBox.PreviewTextInput -= OnExpiryTextInput;
            DataObject.RemovePastingHandler(textBox, OnExpiryPasting);
        }
    }

    private static void OnNumericTextInput(object sender, TextCompositionEventArgs e) 
        => e.Handled = !e.Text.All(c => char.IsDigit(c) || c == ' ');

    private static void OnExpiryTextInput(object sender, TextCompositionEventArgs e) 
        => e.Handled = !e.Text.All(c => char.IsDigit(c) || c == '/');

    private static void OnNumericPasting(object sender, DataObjectPastingEventArgs e)
        => HandlePasting(e, c => char.IsDigit(c) || c == ' ');

    private static void OnExpiryPasting(object sender, DataObjectPastingEventArgs e)
        => HandlePasting(e, c => char.IsDigit(c) || c == '/');

    private static void HandlePasting(DataObjectPastingEventArgs e, Func<char, bool> isValidChar)
    {
        if (e.DataObject.GetDataPresent(typeof(string)))
        {
            var text = (string)e.DataObject.GetData(typeof(string))!;
            if (!text.All(isValidChar))
            {
                e.CancelCommand();
            }
        }
        else
        {
            e.CancelCommand();
        }
    }
}
