<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup><HResourcesGenerator_Namespace>Kassyi.Generators.DependencyProperty</HResourcesGenerator_Namespace><EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles><RootNamespace>Kassyi.Generators.DependencyProperty</RootNamespace>
        <TargetFrameworks>netstandard2.0</TargetFrameworks><!-- ;net6.0;net7.0;net8.0 -->
        <NoWarn>$(NoWarn);CA1014;CA1308;CA1031;CA1307</NoWarn>
        <IsRoslynComponent>true</IsRoslynComponent>
        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    </PropertyGroup>

    <PropertyGroup Label="NuGet">
        <NoWarn>$(NoWarn);NU5128;CA1724</NoWarn>
        <DevelopmentDependency>true</DevelopmentDependency>
        <IncludeBuildOutput>false</IncludeBuildOutput>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
        <Description>C# Source Generator library to generate DependencyProperty.</Description>
        <PackageTags>dependency;property;dependency property;generator;source generator</PackageTags>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="H.Resources.Generator">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="IsExternalInit">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <ProjectReference Include="..\Kassyi.Generators.Extensions\Kassyi.Generators.Extensions.csproj" PrivateAssets="all" OutputItemType="Analyzer" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Kassyi.Generators.DependencyProperty.SnapshotTests" PublicKey="0024000004800000940000000602000000240000525341310004000001000100ada24e42cb0bff239c179aacb191914944e2ded085cd90ccd5d4e6a3b2ba318010787074835efdb34e20234970769b640b043d9d5bcbd878d160bee7422ed77f44e00d909cb4ac8565a2cbc3897115450f244bf6a405ec5c143647e30456957776612c0e1e017173fda4edab9824dece49fe2596fa8fa144754c6ca7876c20c3" />
        <InternalsVisibleTo Include="Kassyi.Generators.DependencyProperty.Tests" PublicKey="0024000004800000940000000602000000240000525341310004000001000100ada24e42cb0bff239c179aacb191914944e2ded085cd90ccd5d4e6a3b2ba318010787074835efdb34e20234970769b640b043d9d5bcbd878d160bee7422ed77f44e00d909cb4ac8565a2cbc3897115450f244bf6a405ec5c143647e30456957776612c0e1e017173fda4edab9824dece49fe2596fa8fa144754c6ca7876c20c3" />
    </ItemGroup>

    <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup Condition=" '$(TargetFramework)' == 'net6.0' ">
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all" VersionOverride="4.11.0" />
    </ItemGroup>

    <ItemGroup Condition=" '$(TargetFramework)' == 'net7.0' ">
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all" VersionOverride="4.11.0" />
    </ItemGroup>

    <ItemGroup Condition=" '$(TargetFramework)' == 'net8.0' ">
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all" VersionOverride="4.11.0" />
    </ItemGroup>
    
    <ItemGroup Label="Attributes">
        <EmbeddedResource Include="../Kassyi.Generators.DependencyProperty.Attributes/*.cs" Visible="false" />
        <AdditionalFiles Include="../Kassyi.Generators.DependencyProperty.Attributes/*.cs" Visible="false" HResourcesGenerator_Resource="true" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference
            Include="..\Kassyi.Generators.DependencyProperty.Attributes\Kassyi.Generators.DependencyProperty.Attributes.csproj"
            PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup Condition=" '$(TargetFramework)' == '' ">
        <None Include="Kassyi.Generators.DependencyProperty.props" Pack="true" PackagePath="build" />
        <None Include="$(OutputPath)\netstandard2.0\Kassyi.Generators.DependencyProperty.dll" Pack="true" PackagePath="analyzers/dotnet/roslyn4.3.1/cs" Visible="false" />
        <None Include="$(OutputPath)\netstandard2.0\Kassyi.Generators.DependencyProperty.Attributes.dll" Pack="true" PackagePath="analyzers/dotnet/roslyn4.3.1/cs" Visible="false" />
        <None Include="$(OutputPath)\netstandard2.0\Kassyi.Generators.Extensions.dll" Pack="true" PackagePath="analyzers/dotnet/roslyn4.3.1/cs" Visible="false" />
<!--        <None Include="$(OutputPath)\net6.0\Kassyi.Generators.DependencyProperty.dll" Pack="true" PackagePath="analyzers/dotnet/roslyn4.6.0/cs" Visible="false" />-->
<!--        <None Include="$(OutputPath)\net6.0\Kassyi.Generators.DependencyProperty.Attributes.dll" Pack="true" PackagePath="analyzers/dotnet/roslyn4.6.0/cs" Visible="false" />-->
<!--        <None Include="$(OutputPath)\net6.0\Kassyi.Generators.Extensions.dll" Pack="true" PackagePath="analyzers/dotnet/roslyn4.6.0/cs" Visible="false" />-->
<!--        <None Include="$(OutputPath)\net7.0\Kassyi.Generators.DependencyProperty.dll" Pack="true" PackagePath="analyzers/dotnet/roslyn4.7.0/cs" Visible="false" />-->
<!--        <None Include="$(OutputPath)\net7.0\Kassyi.Generators.DependencyProperty.Attributes.dll" Pack="true" PackagePath="analyzers/dotnet/roslyn4.7.0/cs" Visible="false" />-->
<!--        <None Include="$(OutputPath)\net7.0\Kassyi.Generators.Extensions.dll" Pack="true" PackagePath="analyzers/dotnet/roslyn4.7.0/cs" Visible="false" />-->
<!--        <None Include="$(OutputPath)\net8.0\Kassyi.Generators.DependencyProperty.dll" Pack="true" PackagePath="analyzers/dotnet/roslyn4.8.0/cs" Visible="false" />-->
<!--        <None Include="$(OutputPath)\net8.0\Kassyi.Generators.DependencyProperty.Attributes.dll" Pack="true" PackagePath="analyzers/dotnet/roslyn4.8.0/cs" Visible="false" />-->
<!--        <None Include="$(OutputPath)\net8.0\Kassyi.Generators.Extensions.dll" Pack="true" PackagePath="analyzers/dotnet/roslyn4.8.0/cs" Visible="false" />-->
    </ItemGroup>

</Project>
