<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>netstandard2.0;net4.5.1</TargetFrameworks>
        <IsPackable>false</IsPackable>
        <Nullable>disable</Nullable>
        <ImplicitUsings>disable</ImplicitUsings>
        <NoWarn>$(NoWarn);IDE0001;IDE0190</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Kassyi.Generators.DependencyProperty" PublicKey="0024000004800000940000000602000000240000525341310004000001000100ada24e42cb0bff239c179aacb191914944e2ded085cd90ccd5d4e6a3b2ba318010787074835efdb34e20234970769b640b043d9d5bcbd878d160bee7422ed77f44e00d909cb4ac8565a2cbc3897115450f244bf6a405ec5c143647e30456957776612c0e1e017173fda4edab9824dece49fe2596fa8fa144754c6ca7876c20c3" />
    </ItemGroup>

</Project>
